### ISSUE TITLE
Comments in action rules

### ISSUE THREAD

**Issue by drasmuss** [nengo/nengo_spa#102]
Following up on #81/#85, it'd be handy to be able to insert comments throughout an action string, e.g.,

```
# explanation of this block
# explanation of this condition
ifmax ...:
    # explanation of this rule
    x -> y
    # explanation of this rule
    y -> z
# explanation of this condition
elifmax 
    ...

# explanation of this block
ifmax ...:
    ...
```

**Comment by jgosmann** [comment]
That should already work (if not please post the exception traceback).

**Comment by drasmuss** [comment]
Here's a traceback:
``` python
    with nengo_spa.Network() as net:
        a = nengo_spa.State(16)
        b = nengo_spa.State(16)
        c = nengo_spa.State(16)
        d = nengo_spa.State(16)

        nengo_spa.Actions("""
            ifmax dot(a, b):
                # comment
                c -> d
            elifmax dot(c, d):
                a -> b
            """)
```
```
Traceback (most recent call last):
  File "d:\documents\nengo_spa\nengo_spa\actions.py", line 84, in Actions
    parse_tree = parse(actions)
  File "d:\documents\nengo_spa\nengo_spa\compiler\grammar.py", line 34, in parse
    BytesIO(code.encode()).readline)))
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 182, in read
    return [x for rule in self.rules for x in rule.read(tokens)]
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 182, in <listcomp>
    return [x for rule in self.rules for x in rule.read(tokens)]
  File "d:\documents\nengo_spa\nengo_spa\compiler\grammar.py", line 158, in read
    match.extend(action.read(tokens))
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 217, in read
    return rule.read(tokens)
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 342, in read
    return [(self.name, self.rule.read(tokens))]
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 182, in read
    return [x for rule in self.rules for x in rule.read(tokens)]
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 182, in <listcomp>
    return [x for rule in self.rules for x in rule.read(tokens)]
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 342, in read
    return [(self.name, self.rule.read(tokens))]
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 182, in read
    return [x for rule in self.rules for x in rule.read(tokens)]
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 182, in <listcomp>
    return [x for rule in self.rules for x in rule.read(tokens)]
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 182, in read
    return [x for rule in self.rules for x in rule.read(tokens)]
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 182, in <listcomp>
    return [x for rule in self.rules for x in rule.read(tokens)]
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 217, in read
    return rule.read(tokens)
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 182, in read
    return [x for rule in self.rules for x in rule.read(tokens)]
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 182, in <listcomp>
    return [x for rule in self.rules for x in rule.read(tokens)]
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 182, in read
    return [x for rule in self.rules for x in rule.read(tokens)]
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 182, in <listcomp>
    return [x for rule in self.rules for x in rule.read(tokens)]
  File "d:\documents\nengo_spa\nengo_spa\compiler\parsing.py", line 148, in read
    raise RuleMismatchError(self, self, tokens.peek()[0])
nengo_spa.compiler.parsing.RuleMismatchError: Could not apply rule 'INDENT'. Expected 'INDENT', but found 'TokenInfo(type=57 (COMMENT), string='# comment', start=(3, 16), end=(3, 25), line='                # comment\n')'.
```
