### ISSUE TITLE
Forgetting to define transcode input/output vocab gives weird error

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo_spa#105]
Running:

```
import nengo_spa as spa

dimensions = 16

with spa.Network() as model:
    model.vision = spa.Transcode(output_vocab=dimensions)
    model.statement = spa.Transcode(output_vocab=dimensions)
    
    actions = spa.Actions('''
        ifmax dot(model.vision, STATEMENT):
            model.vision -> model.statement
    ''')
```

Gives the error:

```
Traceback (most recent call last):
  File "vocab_oops.py", line 20, in <module>
    ''')
  File "/home/saubin/git/nengo_spa/nengo_spa/actions.py", line 93, in Actions
    top_node.infer_types(None)
  File "/home/saubin/git/nengo_spa/nengo_spa/compiler/ast_nodes.py", line 992, in infer_types
    action.infer_types(context_type)
  File "/home/saubin/git/nengo_spa/nengo_spa/compiler/ast_nodes.py", line 921, in infer_types
    self.effects.infer_types(None)
  File "/home/saubin/git/nengo_spa/nengo_spa/compiler/ast_nodes.py", line 828, in infer_types
    e.infer_types(context_type)
  File "/home/saubin/git/nengo_spa/nengo_spa/compiler/ast_nodes.py", line 781, in infer_types
    self.sink.infer_types(None)
  File "/home/saubin/git/nengo_spa/nengo_spa/compiler/ast_nodes.py", line 863, in infer_types
    vocab = Network.get_input_vocab(self.obj)
  File "/home/saubin/git/nengo_spa/nengo_spa/network.py", line 95, in get_input_vocab
    return cls._input_vocabs[obj]
  File "/usr/lib/python3.6/weakref.py", line 394, in __getitem__
    return self.data[ref(key)]
KeyError: <weakref at 0x7f6889b12ea8; to 'Node' at 0x7f6889b2acf8>
```

This code gives a similar error:
```
import nengo_spa as spa

dimensions = 16

with spa.Network() as model:
    model.vision = spa.Transcode(input_vocab=dimensions)
    model.statement = spa.Transcode(output_vocab=dimensions)
    
    actions = spa.Actions('''
        ifmax dot(model.vision, STATEMENT):
            model.vision -> model.statement
    ''')
```

**Comment by jgosmann** [comment]
I'm having a déjà vu, didn't I fix this bug already. 🤔 Anyways I'll have a look.

**Comment by jgosmann** [comment]
The errors I am getting seem reasonable:
```console
SpaTypeError: In effect "model.vision -> model.statement": model.statement <Node (unlabeled) at 0x7f2759e22358> is not declared as input.
SpaTypeError: model.vision <Node (unlabeled) at 0x7f2759dbdcf8> is not declared as output.
```
Did you maybe use an old version?

**Comment by Seanny123** [comment]
Probably.
