### ISSUE TITLE
Better error on failure to infer types

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo_spa#82]
I'm re-implementing [Spaun's counting network using `nengo_spa`](https://github.com/Seanny123/simple_count). When I run `python count.py` from the linked repository, I get the following error:
```
Traceback (most recent call last):
  File "count.py", line 148, in <module>
    """)
  File "/home/saubin/git/nengo_spa/nengo_spa/actions.py", line 80, in Actions
    top_node.infer_types(None)
  File "/home/saubin/git/nengo_spa/nengo_spa/compiler/ast_nodes.py", line 992, in infer_types
    action.infer_types(context_type)
  File "/home/saubin/git/nengo_spa/nengo_spa/compiler/ast_nodes.py", line 915, in infer_types
    self.condition.infer_types(context_type)
  File "/home/saubin/git/nengo_spa/nengo_spa/compiler/ast_nodes.py", line 444, in infer_types
    context_type = infer_vocab(self.lhs, self.rhs)
  File "/home/saubin/git/nengo_spa/nengo_spa/compiler/ast_nodes.py", line 62, in infer_vocab
    node.infer_types(None)
  File "/home/saubin/git/nengo_spa/nengo_spa/compiler/ast_nodes.py", line 444, in infer_types
    context_type = infer_vocab(self.lhs, self.rhs)
  File "/home/saubin/git/nengo_spa/nengo_spa/compiler/ast_nodes.py", line 62, in infer_vocab
    node.infer_types(None)
  File "/home/saubin/git/nengo_spa/nengo_spa/compiler/ast_nodes.py", line 444, in infer_types
    context_type = infer_vocab(self.lhs, self.rhs)
  File "/home/saubin/git/nengo_spa/nengo_spa/compiler/ast_nodes.py", line 62, in infer_vocab
    node.infer_types(None)
  File "/home/saubin/git/nengo_spa/nengo_spa/compiler/ast_nodes.py", line 360, in infer_types
    vocab = Network.get_output_vocab(self.obj)
  File "/home/saubin/git/nengo_spa/nengo_spa/network.py", line 85, in get_output_vocab
    return cls._output_vocabs[obj]
  File "/usr/lib/python3.6/weakref.py", line 394, in __getitem__
    return self.data[ref(key)]
KeyError: <weakref at 0x7fa55aab4ef8; to 'Node' at 0x7fa55aae55c0>
```

I don't expect anyone to clone my repository and run it themselves, but I was hoping to get some tips for isolating the error better, so I can report a better bug. How can I isolate what line of giant `spa.Actions` is causing this error?

**Comment by jgosmann** [comment]
I think nengo_spa is failing to find find the output vocabulary for a module, potentially because [this line](https://github.com/Seanny123/simple_count/blob/master/mem_net.py#L19) says `declare_input` instead of `declare_output`.

Can you verify this? If so, this case should definitely give a better error message.

**Comment by Seanny123** [comment]
Surprisingly, that wasn't what caused the error. I fixed that typo and I still get the same error.

**Comment by Seanny123** [comment]
So there's actually two causes for this error. The first is trying to connect to the input of a `spa.Network` as an output. The minimal code to reproduce this error is:

```
import nengo
import nengo_spa as spa


class MemNet(spa.Network):
    def __init__(self, mem_vocab):
        super(MemNet, self).__init__()

        self.output = nengo.Node(size_in=mem_vocab.dimensions)

        self.declare_output(self.output, mem_vocab)

num_vocab = spa.Vocabulary(16)

with spa.Network() as model:

    model.res_mem = MemNet(num_vocab)
    model.motor = spa.State(num_vocab)

    spa.Actions("""
        model.res_mem -> model.motor
    """)
```

**Comment by Seanny123** [comment]
The second way to produce this error is a bit weirder and I can't really explain why it happens:

```
import nengo
import nengo_spa as spa

num_vocab = spa.Vocabulary(16)

with spa.Network() as model:

    model.motor_mag = spa.Scalar()

    model.running = spa.Transcode(input_vocab=num_vocab)
    model.scal = spa.Scalar()

    spa.Actions("""
        model.running + model.scal -> model.motor_mag
    """)
```

Note that defining an output vocab for `model.running` gives a more readable error. For example:

```
import nengo
import nengo_spa as spa

num_vocab = spa.Vocabulary(16)

with spa.Network() as model:

    model.motor_mag = spa.Scalar()

    model.running = spa.Transcode(input_vocab=num_vocab, output_vocab=num_vocab)
    model.scal = spa.Scalar()

    spa.Actions("""
        model.running + model.scal -> model.motor_mag
    """)
```

Gives the understandable type mismatch error:

```
Traceback (most recent call last):
  File "trans_fail.py", line 15, in <module>
    """)
  File "/home/saubin/git/nengo_spa/nengo_spa/actions.py", line 80, in Actions
    top_node.infer_types(None)
  File "/home/saubin/git/nengo_spa/nengo_spa/compiler/ast_nodes.py", line 782, in infer_types
    self.source.infer_types(self.sink.type)
  File "/home/saubin/git/nengo_spa/nengo_spa/compiler/ast_nodes.py", line 458, in infer_types
    self.lhs.type, self.rhs.type, self))
nengo_spa.exceptions.SpaTypeError: Incompatible types TVocabulary<16-dimensional vocab at 0x7f8a9ce95dd8> and TScalar in operation 'model.running + model.scal'.
```

**Comment by jgosmann** [comment]
> The second way to produce this error is a bit weirder and I can't really explain why it happens:

Because you are not providing an output vocabulary, transcode does not have an output, but you are accessing the output in your action rule.
