### ISSUE TITLE
Node output of spa.Network needs size_in?

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo_spa#83]
When I run the following code:

```
import nengo
import nengo_spa as spa


class MemNet(spa.Network):
    def __init__(self, mem_vocab):
        super(MemNet, self).__init__()

        self.output = nengo.Node(size_out=mem_vocab.dimensions)

        self.declare_output(self.output, mem_vocab)

num_vocab = spa.Vocabulary(16)

with spa.Network() as model:

    model.res_mem = MemNet(num_vocab)
    model.motor = spa.State(num_vocab)

    spa.Actions("""
        model.res_mem -> model.motor
    """)
```

I get the error:
```
Traceback (most recent call last):
  File "super_bad_out_fail.py", line 22, in <module>
    """)
  File "/home/saubin/git/nengo_spa/nengo_spa/actions.py", line 83, in Actions
    top_node.construct(construction_context)
  File "/home/saubin/git/nengo_spa/nengo_spa/compiler/ast_nodes.py", line 807, in construct
    artifact.nengo_source, target, transform=artifact.transform))
  File "/home/saubin/git/nengo/nengo/base.py", line 35, in __call__
    inst.__init__(*args, **kwargs)
  File "/home/saubin/git/nengo/nengo/connection.py", line 419, in __init__
    self.pre = pre
  File "/home/saubin/git/nengo/nengo/base.py", line 106, in __setattr__
    super(NengoObject, self).__setattr__(name, val)
  File "/home/saubin/git/nengo/nengo/config.py", line 456, in __setattr__
    reraise(exc_info[0], exc_info[1], None)
  File "/home/saubin/git/nengo/nengo/utils/compat.py", line 97, in reraise
    raise value.with_traceback(tb)
nengo.exceptions.ValidationError: Connection.pre: '<Node (unlabeled) at 0x7f2ef762d278>' must have size_out > 0.
```
 
I honestly don't know if:
1. Is this a valid error?
2. If this is a valid error, is there a better way of displaying it?

**Comment by jgosmann** [comment]
1. Yes, this is a valid error because the `size_out` is indeed 0.
2. Maybe, but this is a Nengo core issue. In fact, there is an additional warning (that might not be displayed in some environments) which tells you the actual problem with this code:
```
/home/jgosmann/Documents/projects/nengo/nengo/node.py:42: UserWarning: 'Node.size_out' is being overwritten with 'Node.size_in' since 'Node.output=None'
```
